import DataGridMongo from "@/components/dataGridMongo";
import FirstPage from "@/components/1stPage";
import NavBar from "@/components/navBar";
import SideBar from "@/components/sideBar";
import Head from "next/head";
import useSwr from "swr";
import { useSession, signIn, signOut } from "next-auth/react";
import { useRouter } from "next/router";
import AdminOnly from "@/components/adminOnly";

export default function Home() {
  const { data: session, status } = useSession();
  const URL = `${process.env.NEXT_PUBLIC_URL}/api/v1/theme`;
  const router = useRouter();
  const tab = parseInt(router.query.tab);

  async function fetchThemeData() {
    const res = await fetch(URL);
    return res.json();
  }

  const { data, isLoading } = useSwr("themeData", fetchThemeData);

  if (isLoading) return null;

  const buttonColor = data.theme[0].buttonValue;
  const theme = data.theme[0];

  const dataGridIcons = {
    addIcon: theme.addDataIcon,
    editIcon: theme.editDataIcon,
    deleteIcon: theme.deleteDataIcon,
  };

  const navIcons = {
    logo: theme.logo,
    helpIcon: theme.helpIcon,
    aboutIcon: theme.aboutIcon,
    userIcon: theme.userIcon,
    logoutIcon: theme.logoutIcon,
    loginIcon: theme.loginIcon,
  };

  const sidebarIcons = {
    homeIcon: theme.homeIcon,
    dataIcon: theme.dataIcon,
    adminIcon: theme.adminIcon,
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavBar
          navIcons={navIcons}
          login={signIn}
          logout={signOut}
          status={status}
          buttonColor={buttonColor}
          user={session?.user}
        />

        <div className="grid grid-cols-12 ">
          <SideBar sidebarIcons={sidebarIcons} buttonColor={buttonColor} />
          <div className="col-span-12 md:col-span-10 px-5 xl:px-10 py-6">
            {!tab && <FirstPage />}
            {tab === 1 && (
              <DataGridMongo
                dataIcons={dataGridIcons}
                buttonColor={buttonColor}
              />
            )}
            {session?.user && tab === 2 && (
              <AdminOnly
                theme={theme}
                buttonColor={buttonColor}
                user={session?.user}
              />
            )}
          </div>
        </div>
      </main>
    </>
  );
}
